using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Creates and manages Unity geometry generated by AI.
///
/// Supported tools:
///     create_primitive
///     create_wall
///     move_object
///     resize_object
///     delete_object
///     clear_house
///
/// Uses the shared ToolArguments and WallPoint
/// classes from AIToolData.cs.
/// </summary>
public class UnityToolManager : MonoBehaviour
{
    [Header("Generated House")]
    [SerializeField]
    private Transform generatedHouseParent;

    [Header("Materials")]
    [SerializeField]
    private Material wallMaterial;

    [SerializeField]
    private Material defaultMaterial;

    [Header("Default Wall Settings")]
    [SerializeField]
    private float defaultWallHeight = 2.7f;

    [SerializeField]
    private float defaultWallThickness = 0.15f;

    private readonly List<GameObject> generatedObjects =
        new List<GameObject>();


    // =========================================================
    // TOOL EXECUTION
    // =========================================================

    public void ExecuteTool(
        string tool,
        ToolArguments args)
    {
        if (string.IsNullOrWhiteSpace(tool))
        {
            Debug.LogWarning(
                "UnityToolManager: Tool name is empty."
            );

            return;
        }

        // clear_house does not require arguments
        if (tool != "clear_house" && args == null)
        {
            Debug.LogWarning(
                "UnityToolManager: Tool arguments are null."
            );

            return;
        }

        switch (tool)
        {
            case "create_primitive":

                CreatePrimitive(args);

                break;


            case "create_wall":

                CreateWallFromArguments(args);

                break;


            case "move_object":

                MoveObject(args);

                break;


            case "resize_object":

                ResizeObject(args);

                break;


            case "delete_object":

                DeleteObject(args);

                break;


            case "clear_house":

                ClearGeneratedHouse();

                break;


            default:

                Debug.LogWarning(
                    "UnityToolManager: Unknown tool: " +
                    tool
                );

                break;
        }
    }


    // =========================================================
    // CREATE PRIMITIVE
    // =========================================================

    private void CreatePrimitive(
        ToolArguments args)
    {
        if (string.IsNullOrWhiteSpace(args.objectType))
        {
            Debug.LogWarning(
                "CreatePrimitive: objectType is empty."
            );

            return;
        }

        PrimitiveType primitiveType;

        switch (
            args.objectType.ToLowerInvariant())
        {
            case "cube":

                primitiveType =
                    PrimitiveType.Cube;

                break;


            case "sphere":

                primitiveType =
                    PrimitiveType.Sphere;

                break;


            case "cylinder":

                primitiveType =
                    PrimitiveType.Cylinder;

                break;


            case "capsule":

                primitiveType =
                    PrimitiveType.Capsule;

                break;


            case "plane":

                primitiveType =
                    PrimitiveType.Plane;

                break;


            case "quad":

                primitiveType =
                    PrimitiveType.Quad;

                break;


            default:

                Debug.LogWarning(
                    "Unknown primitive: " +
                    args.objectType
                );

                return;
        }


        GameObject obj =
            GameObject.CreatePrimitive(
                primitiveType
            );


        // Use AI supplied name
        // otherwise generate one.
        string objectName =
            string.IsNullOrWhiteSpace(args.name)
                ? "AI_" + args.objectType
                : args.name;


        obj.name =
            MakeUniqueName(
                objectName
            );


        obj.transform.position =
            args.position;


        obj.transform.rotation =
            Quaternion.Euler(
                args.rotation
            );


        Vector3 scale =
            args.scale;

        if (scale == Vector3.zero)
        {
            scale =
                Vector3.one;
        }

        obj.transform.localScale =
            scale;


        ApplyMaterial(
            obj,
            defaultMaterial
        );


        ApplyColor(
            obj,
            args.color
        );


        SetParent(
            obj,
            generatedHouseParent
        );


        generatedObjects.Add(
            obj
        );


        Debug.Log(
            "Created primitive: " +
            obj.name
        );
    }


    // =========================================================
    // CREATE WALL FROM AI
    // =========================================================

    private void CreateWallFromArguments(
        ToolArguments args)
    {
        string wallName =
            string.IsNullOrWhiteSpace(args.name)
                ? "AI_Wall"
                : args.name;


        float height =
            args.height > 0
                ? args.height
                : defaultWallHeight;


        float thickness =
            args.thickness > 0
                ? args.thickness
                : defaultWallThickness;


        CreateWall(
            wallName,

            new WallPoint
            {
                x = args.startX,
                z = args.startZ
            },

            new WallPoint
            {
                x = args.endX,
                z = args.endZ
            },

            height,

            thickness,

            generatedHouseParent
        );
    }


    // =========================================================
    // CREATE WALL
    // =========================================================

    public bool CreateWall(
        string wallName,
        WallPoint start,
        WallPoint end,
        float height,
        float thickness,
        Transform parent)
    {
        if (start == null || end == null)
        {
            Debug.LogWarning(
                "CreateWall: Invalid start/end."
            );

            return false;
        }


        Vector3 startPosition =
            new Vector3(
                start.x,
                0f,
                start.z
            );


        Vector3 endPosition =
            new Vector3(
                end.x,
                0f,
                end.z
            );


        Vector3 direction =
            endPosition -
            startPosition;


        float length =
            direction.magnitude;


        if (length < 0.05f)
        {
            Debug.LogWarning(
                "CreateWall: Wall is too short."
            );

            return false;
        }


        Vector3 midpoint =
            (startPosition +
             endPosition) *
            0.5f;


        GameObject wall =
            GameObject.CreatePrimitive(
                PrimitiveType.Cube
            );


        wall.name =
            MakeUniqueName(
                string.IsNullOrWhiteSpace(wallName)
                    ? "AI_Wall"
                    : wallName
            );


        wall.transform.position =
            midpoint +
            Vector3.up *
            (height * 0.5f);


        wall.transform.rotation =
            Quaternion.LookRotation(
                direction.normalized,
                Vector3.up
            );


        wall.transform.localScale =
            new Vector3(
                thickness,
                height,
                length
            );


        SetParent(
            wall,
            parent
        );


        ApplyMaterial(
            wall,
            wallMaterial
        );


        generatedObjects.Add(
            wall
        );


        Debug.Log(
            "Created wall: " +
            wall.name +
            " | Length: " +
            length.ToString("F2") +
            "m"
        );


        return true;
    }


    // =========================================================
    // MOVE OBJECT
    // =========================================================

    private void MoveObject(
        ToolArguments args)
    {
        if (string.IsNullOrWhiteSpace(args.targetName))
        {
            Debug.LogWarning(
                "MoveObject: targetName is empty."
            );

            return;
        }


        GameObject target =
            FindGeneratedObject(
                args.targetName
            );


        if (target == null)
        {
            Debug.LogWarning(
                "MoveObject: Could not find " +
                args.targetName
            );

            return;
        }


        Vector3 movement =
            new Vector3(
                args.moveX,
                args.moveY,
                args.moveZ
            );


        target.transform.position +=
            movement;


        Debug.Log(
            "Moved " +
            target.name +
            " by " +
            movement
        );
    }


    // =========================================================
    // RESIZE OBJECT
    // =========================================================

    private void ResizeObject(
        ToolArguments args)
    {
        if (string.IsNullOrWhiteSpace(args.targetName))
        {
            Debug.LogWarning(
                "ResizeObject: targetName is empty."
            );

            return;
        }


        GameObject target =
            FindGeneratedObject(
                args.targetName
            );


        if (target == null)
        {
            Debug.LogWarning(
                "ResizeObject: Could not find " +
                args.targetName
            );

            return;
        }


        Vector3 currentScale =
            target.transform.localScale;


        Vector3 newScale =
            currentScale;


        if (args.scaleX > 0)
        {
            newScale.x =
                args.scaleX;
        }


        if (args.scaleY > 0)
        {
            newScale.y =
                args.scaleY;
        }


        if (args.scaleZ > 0)
        {
            newScale.z =
                args.scaleZ;
        }


        target.transform.localScale =
            newScale;


        Debug.Log(
            "Resized " +
            target.name +
            " to " +
            newScale
        );
    }


    // =========================================================
    // DELETE OBJECT
    // =========================================================

    private void DeleteObject(
        ToolArguments args)
    {
        if (string.IsNullOrWhiteSpace(args.targetName))
        {
            Debug.LogWarning(
                "DeleteObject: targetName is empty."
            );

            return;
        }


        GameObject target =
            FindGeneratedObject(
                args.targetName
            );


        if (target == null)
        {
            Debug.LogWarning(
                "DeleteObject: Could not find " +
                args.targetName
            );

            return;
        }


        generatedObjects.Remove(
            target
        );


        Destroy(
            target
        );


        Debug.Log(
            "Deleted: " +
            args.targetName
        );
    }


    // =========================================================
    // FIND GENERATED OBJECT
    // =========================================================

    private GameObject FindGeneratedObject(
        string objectName)
    {
        for (
            int i = 0;
            i < generatedObjects.Count;
            i++)
        {
            GameObject obj =
                generatedObjects[i];


            if (obj == null)
            {
                continue;
            }


            if (
                string.Equals(
                    obj.name,
                    objectName,
                    StringComparison.OrdinalIgnoreCase
                )
            )
            {
                return obj;
            }
        }


        return null;
    }


    // =========================================================
    // UNIQUE NAME
    // =========================================================

    private string MakeUniqueName(
        string requestedName)
    {
        if (string.IsNullOrWhiteSpace(requestedName))
        {
            requestedName =
                "AI_Object";
        }


        if (
            FindGeneratedObject(
                requestedName
            ) == null
        )
        {
            return requestedName;
        }


        int counter = 2;


        while (true)
        {
            string candidate =
                requestedName +
                "_" +
                counter;


            if (
                FindGeneratedObject(
                    candidate
                ) == null
            )
            {
                return candidate;
            }


            counter++;
        }
    }


    // =========================================================
    // APPLY MATERIAL
    // =========================================================

    private void ApplyMaterial(
        GameObject obj,
        Material material)
    {
        if (obj == null)
            return;


        Renderer renderer =
            obj.GetComponent<Renderer>();


        if (renderer == null)
            return;


        if (material != null)
        {
            renderer.material =
                material;

            return;
        }


        Shader shader =
            Shader.Find(
                "Universal Render Pipeline/Lit"
            );


        if (shader == null)
        {
            shader =
                Shader.Find(
                    "Standard"
                );
        }


        if (shader == null)
        {
            Debug.LogWarning(
                "UnityToolManager: " +
                "Could not find shader."
            );

            return;
        }


        Material newMaterial =
            new Material(shader);


        newMaterial.color =
            new Color(
                0.75f,
                0.75f,
                0.75f
            );


        renderer.material =
            newMaterial;
    }


    // =========================================================
    // APPLY COLOR
    // =========================================================

    private void ApplyColor(
        GameObject obj,
        string hexColor)
    {
        if (obj == null)
            return;


        if (string.IsNullOrWhiteSpace(hexColor))
            return;


        Renderer renderer =
            obj.GetComponent<Renderer>();


        if (renderer == null)
            return;


        Color color;


        if (
            ColorUtility.TryParseHtmlString(
                hexColor,
                out color
            )
        )
        {
            renderer.material.color =
                color;
        }
    }


    // =========================================================
    // SET PARENT
    // =========================================================

    private void SetParent(
        GameObject obj,
        Transform parent)
    {
        if (obj == null)
            return;


        if (parent != null)
        {
            obj.transform.SetParent(
                parent,
                true
            );
        }
    }


    // =========================================================
    // CLEAR GENERATED HOUSE
    // =========================================================

    public void ClearGeneratedHouse()
    {
        for (
            int i =
                generatedObjects.Count - 1;
            i >= 0;
            i--
        )
        {
            GameObject obj =
                generatedObjects[i];


            if (obj != null)
            {
                Destroy(obj);
            }
        }


        generatedObjects.Clear();


        Debug.Log(
            "UnityToolManager: " +
            "Generated house cleared."
        );
    }


    // =========================================================
    // PUBLIC TEST FUNCTIONS
    // =========================================================

    // These are useful for testing from Unity's Inspector
    // before connecting Ollama.

    public void TestCreateCube()
    {
        ToolArguments args =
            new ToolArguments();

        args.objectType =
            "cube";

        args.name =
            "TestCube";

        args.position =
            new Vector3(
                0f,
                0.5f,
                0f
            );

        args.scale =
            new Vector3(
                1f,
                1f,
                1f
            );

        args.color =
            "#00FF00";

        ExecuteTool(
            "create_primitive",
            args
        );
    }


    public void TestCreateWall()
    {
        ToolArguments args =
            new ToolArguments();

        args.name =
            "TestWall";

        args.startX =
            -2f;

        args.startZ =
            0f;

        args.endX =
            2f;

        args.endZ =
            0f;

        args.height =
            2.7f;

        args.thickness =
            0.15f;

        ExecuteTool(
            "create_wall",
            args
        );
    }


    public void TestMoveCube()
    {
        ToolArguments args =
            new ToolArguments();

        args.targetName =
            "TestCube";

        args.moveX =
            1f;

        args.moveY =
            0f;

        args.moveZ =
            0f;

        ExecuteTool(
            "move_object",
            args
        );
    }


    public void TestDeleteCube()
    {
        ToolArguments args =
            new ToolArguments();

        args.targetName =
            "TestCube";

        ExecuteTool(
            "delete_object",
            args
        );
    }
}